@startuml
node "Atoms" {
    package "Buttons" {
        [Button]
        [Cta Button]
        [Mood Button]
    }
    package "Headings" {
        [PrimaryHeading]
        [SecondaryHeading]
    }
    [Tag]
    [Textfield]
    [DatePicker]
    [Icon]
}

node "Molecules" {
    [Card]
    [CircularProgressBar]
}

node "Organisms" {
    package "Modals" {
        [ReportMoodModal]
    }
    package "Cards" {
        [ProfileCard]
        [WelcomeCard]
        [StatisticsCard]
    }
}

node "Pages" {
    [Start]
    [Panel]
    [Statistics]
}

node "Sass" {
    [Colors]
    [Grid]
    [Mixins]
    [Reset]
}

node "API" {
    [BeeWell]
}
@enduml