@startuml
node "Atoms" {
    package "Buttons" {
        [Button]
        [Cta Button]
        [Mood Button]
    }
    package "Headings" {
        [PrimaryHeading]
        [SecondaryHeading]
    }
    [Tag]
    [Textfield]
    [DatePicker]
    [Icon]
}

node "Molecules" {
    [Card]
    [CircularProgressBar]
    [Graph]
    [Modal]
}

node "Organisms" {
    package "Modals" {
        [ReportMoodModal]
        [SignUpModal]
        [SignInModal]
    }
    package "Cards" {
        [ProfileCard]
        [WelcomeCard]
        [OverviewCard]
        [ReportCard]
        [FilterCard]
        [BestDayCard]
        [BestHourCard]
        [ReportAmountCard]
    }
}

node "Pages" {
    [Start]
    [Panel]
    [Statistics]
}

node "Sass" {
    [Colors]
    [Grid]
    [Mixins]
    [Reset]
}

node "API" {
    [BeeWell]
}
@enduml